services:
  - type: web
    name: financial-assistance-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node server.js
    rootDir: backend
    autoDeploy: true
